# Taksit 

Selvitetään, onko ollut vaikutusta auton hintaan, jos auto on ollut aiemmin taksikäytössä. 

Ladataan aineisto osittain, mukaan seuraavat sarakkeet:

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Tiedoston polku: 
file_path = '/Volumes/AIDA/AIDA-projekti/used_cars_data.csv' 

# Valitut sarakkeet:
sarakkeet = ['make_name', 'model_name', 'mileage', 'year', 'price', 'isCab', 'daysonmarket', 'has_accidents']

# Luetaan aineistosta vain halutut sarakkeet datakehikkoon:
df = pd.read_csv(file_path, usecols = sarakkeet) 

Tutkitaan saatua datakehikkoa.

In [3]:
df.sample(10)

daysonmarket has_accidents  isCab  make_name  mileage  \
152491             21         False  False       Audi   9892.0   
999217             16         False  False       Ford  54003.0   
1753363            35         False   True        GMC  41770.0   
1774740            58         False  False    Hyundai  76356.0   
712726             16           NaN    NaN        GMC      3.0   
2831813            72           NaN    NaN       Audi     10.0   
271842             48         False  False  Chevrolet  36477.0   
1455987             7           NaN    NaN      Mazda      0.0   
787169            286           NaN    NaN       Ford      5.0   
1565588            24         False  False      Honda  13255.0   

                model_name    price  year  
152491                  S4  48100.0  2019  
999217       Fusion Hybrid  14221.0  2017  
1753363           Yukon XL  47139.0  2019  
1774740     Santa Fe Sport  15423.0  2016  
712726         Sierra 1500  57975.0  2020  
2831813  Q5 Hybrid Plug-in  59670.0  2020  
271842             Bolt EV  20995.0  2017  
1455987               CX-5  38900.0  2021  
787169                Edge  43470.0  2020  
1565588             Accord  24988.0  2019

Tässä kysymyksessä on olennaista tietää, onko auto ollut taksikäytössä. Tutkitaan siis ensimmäiseksi, onko sarakkeessa *'isCab'* tyhjiä arvoja, ja poistetaan tarvittaessa tällaiset rivit. 

In [4]:
df['isCab'].unique()

array([nan, False, True], dtype=object)

In [7]:
# Tarkastetaan, montako tyhjää arvoa sarakkeessa 'isCab' on:
df['isCab'].isna().sum()

1426595

In [16]:
# Poistetaan sarakkeessa 'isCab' tyhjän arvon sisältävät rivit:
df.dropna(subset=['isCab'], inplace=True)

# Tarkastetaan uudelleen tyhjien arvojen määrät sarakkeittain:
df.isna().sum()

daysonmarket         0
has_accidents        0
isCab                0
make_name            0
mileage          19390
model_name           0
price                0
year                 0
dtype: int64

Aineisto sisältää yhä tyhjiä arvoja sarakkeessa *'mileage'*. Sopivia keskilukuja näiden korvaamiseksi on vaikea päätellä, joten poistetaan myös nämä rivit.

In [17]:
df.dropna(subset=['mileage'], inplace=True)

df.isna().sum()

daysonmarket     0
has_accidents    0
isCab            0
make_name        0
mileage          0
model_name       0
price            0
year             0
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1554055 entries, 5 to 3000039
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype  
---  ------         --------------    -----  
 0   daysonmarket   1554055 non-null  int64  
 1   has_accidents  1554055 non-null  object 
 2   isCab          1554055 non-null  object 
 3   make_name      1554055 non-null  object 
 4   mileage        1554055 non-null  float64
 5   model_name     1554055 non-null  object 
 6   price          1554055 non-null  float64
 7   year           1554055 non-null  int64  
dtypes: float64(2), int64(2), object(4)
memory usage: 106.7+ MB


Aineistossa on yhä liki 1,6 miljoonaa riviä, kun siitä on poistettu tyhjiä arvoja sisältävät rivit.   

Muutetaan seuraavaksi *'object'*-tyypin sarakkeiden *'has_accidents'* ja *'isCab'* tietotyypiksi *'Boolean'*:

In [36]:
df['isCab'].unique()

array([False,  True])

In [34]:
df['isCab'].unique()

array([False,  True])

In [37]:
df['has_accidents'] = df['has_accidents'].astype(bool)
df['isCab'] = df['isCab'].astype(bool)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1554055 entries, 5 to 3000039
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype  
---  ------         --------------    -----  
 0   daysonmarket   1554055 non-null  int64  
 1   has_accidents  1554055 non-null  bool   
 2   isCab          1554055 non-null  bool   
 3   make_name      1554055 non-null  object 
 4   mileage        1554055 non-null  float64
 5   model_name     1554055 non-null  object 
 6   price          1554055 non-null  float64
 7   year           1554055 non-null  int64  
 8   name           1554055 non-null  object 
dtypes: bool(2), float64(2), int64(2), object(3)
memory usage: 97.8+ MB


Yhdistetään lopuksi *'make_name'* ja *'model_name'* yhdeksi sarakkeeksi *'name'*:

In [31]:
df['name'] = df['make_name'] + " " + df['model_name']

In [32]:
df.head()

daysonmarket  has_accidents  isCab   make_name  mileage  \
5            242          False  False  Land Rover     12.0   
9            510          False  False  Land Rover    254.0   
10          1252          False  False  Alfa Romeo    301.0   
12          1233          False  False         BMW   6903.0   
36            33          False  False     Hyundai  30707.0   

            model_name    price  year                           name  
5    Range Rover Velar  66903.0  2020   Land Rover Range Rover Velar  
9   Range Rover Evoque  84399.0  2020  Land Rover Range Rover Evoque  
10                  4C  97579.0  2015                  Alfa Romeo 4C  
12            3 Series  58995.0  2016                   BMW 3 Series  
36             Elantra  13324.0  2017                Hyundai Elantra

Data on nyt valmis analyysiä varten. Tallennetaan se myöhempää käyttöä varten uudeksi CSV-tiedostoksi *'taksi_data.csv'*:

In [39]:
df.to_csv("taksi_data.csv", index = False)